# Generated by Django 6.0.3 on 2026-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badge_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='badge_number',
            field=models.CharField(blank=True, help_text='Auto-generated: [ROLE]-[YEAR]-NNN', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('POLICE', 'Police'), ('FSL', 'Forensic Science Laboratory'), ('EVIDENCE_ROOM', 'Evidence Room Staff'), ('JUDICIARY', 'Judiciary')], max_length=20),
        ),
    ]
