# Generated by Django 6.0.3 on 2026-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_badge_id_customuser_badge_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badge_number',
            field=models.CharField(blank=True, help_text='Auto-generated: [ROLE]-[YEAR]-NNN', max_length=30, unique=True),
        ),
    ]
