# Generated by Django 6.0.3 on 2026-03-20 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('DIGITAL', 'Digital Media'), ('DOCUMENT', 'Document'), ('BIOLOGICAL', 'Biological'), ('PHYSICAL', 'Physical Object'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('sha512_hash', models.CharField(help_text='SHA-512 hex digest computed at upload time', max_length=128)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('is_verified', models.BooleanField(default=False, help_text='True after at least one successful integrity check')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence File',
                'verbose_name_plural': 'Evidence Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
