# Generated by Django 6.0.3 on 2026-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='custody_status',
            field=models.CharField(choices=[('FSL', 'With FSL'), ('IN_TRANSIT', 'In Transit'), ('EVIDENCE_ROOM', 'Evidence Room'), ('POLICE', 'Police Custody')], default='FSL', max_length=20),
        ),
    ]
