# Generated by Django 6.0.3 on 2026-03-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidencefile_custody_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='current_custodian',
            field=models.ForeignKey(help_text='The officer currently responsible for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_currently_held', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='custody_status',
            field=models.CharField(choices=[('PENDING_TRANSFER', 'Pending Transfer'), ('IN_FSL', 'In FSL Lab'), ('IN_EVIDENCE_ROOM', 'In Evidence Room'), ('IN_POLICE_CUSTODY', 'In Police Custody')], default='IN_FSL', max_length=30),
        ),
    ]
