# Generated by Django 6.0.3 on 2026-03-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, help_text="Django model name that triggered this log entry (e.g. 'EvidenceFile')", max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('UPLOAD', 'File Upload'), ('CHECK', 'Hash Check'), ('VIEW', 'View / Download'), ('TRANSFER', 'Custody Transfer'), ('INTEGRITY_FAIL', 'Integrity Failure'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted')], max_length=20),
        ),
    ]
