# Generated by Django 6.0.3 on 2026-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_activitylog_model_name_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='prev_hash',
            field=models.CharField(blank=True, help_text="Previous entry's signature (Chain of Trust).", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='sha512_hash',
            field=models.CharField(blank=True, help_text="Current entry's SHA-512 cryptographic signature.", max_length=128, null=True),
        ),
    ]
